### ISSUE TITLE
so when I am trying to give my repo link in project section the contents are not displayed in webpage 

### ISSUE THREAD

**Issue by gokuljs** [bodhish/mytemplate.xyz#18]
![image](https://user-images.githubusercontent.com/51263906/129459241-5e5538ba-0216-43a1-ad10-cf8de4f4e92b.png)
so you can clearly see that I am trying to upload and those contents are not shown on the webpage is there any idea how to work around this problem.

**Comment by bodhish** [comment]
@gokuljs Thanks for testing out `mytemplate` . 

It looks like you have entered the GitHub URL for the repository. Try replacing it with `author_slug/repo_slug`

Here is an example 
```ruby
# Link 1
gokuljs/machine-monitoring-tool-using-python-
# Link 2
gokuljs/Node.js-Mongodb-and-Express
```
The output will as follows 
![image](https://user-images.githubusercontent.com/14979190/130333455-d4caef3a-88ab-4cb3-a3c7-8aa6c15c027a.png)
